export const SUPABASE_URL = 'https://ikthwwisvmiypkmfmbvh.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdGh3d2lzdm1peXBrbWZtYnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1MzQ5NzYsImV4cCI6MjA0OTExMDk3Nn0.zr8ap_lt45UlLEW8pmxXwcyrlDjR51KSa5_ILdi4y1Y';


//export const SUPABASE_URL = 'https://jaxszuukknuokcpnnbud.supabase.co';
//export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpheHN6dXVra251b2tjcG5uYnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjUzNTUzMzksImV4cCI6MjA0MDkzMTMzOX0.4nkGUB-toFoPicIkvLjH0HzdPIhcLVld8JNlMZiU8_U';


//export const SUPABASE_URL = 'https://eziwjsienbxkhwpehtgp.supabase.co';
//export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6aXdqc2llbmJ4a2h3cGVodGdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU5NDgwMTEsImV4cCI6MjA0MTUyNDAxMX0.sTP2xX0AK2lNoIVaFxMOPiTWNmiT1Xvmd0bxoKzbKTs';
